### ISSUE TITLE
Possible to add Aurora as an additional data source?

### ISSUE THREAD

**Issue by tr-kory** [aws-quickstart/quickstart-trendmicro-deepsecurity#25]
Hi there.  May I make the suggestion of also incorporating Aurora as a possible data source in addition to RDS?  

Thanks much, in advance.

Regards,
Kory

**Comment by tr-kory** [comment]
Checking on this.

**Comment by HelloFive** [comment]
Hi Kory,

Thank you for your suggestion.
Incorporating Aurora as a possible data source is a good idea. I will pass your suggestion to the product manager for prioritization. But there's no timeline at the moment.

Best regards,
Jason Park

**Comment by tr-kory** [comment]
Sounds good, Jason, thanks!
