### ISSUE TITLE
Getting Error on Wait Condition

### ISSUE THREAD

**Issue by jaekunchoi** [aws-quickstart/quickstart-trendmicro-deepsecurity#29]
I'm getting below error when creating the stack in existing VPC

DSM1CompleteWaitCondition | WaitCondition received failed message: 'DSM Node configuration complete' for uniqueId: i-029b76651bfb6bd0d

What would be the cause of this?

**Comment by vkeyur** [comment]
Current Timeout for WaitHandle is set for 1800, modify to 3600 in master-mp.yml

**Comment by justjais** [comment]
@hybmg57 I am facing the same timeout issue, have tried increasing the timeout value to 3600 but it didn’t help.
