### ISSUE TITLE
eu-west-2 AMI Id not right in DSM template mapping

### ISSUE THREAD

**Issue by kvaibhawa** [aws-quickstart/quickstart-trendmicro-deepsecurity#34]
eu-west-2 AMI Id not right in DSM template mapping. It throws an error and need to update the subscribed Marketplace AMI ID. Let me know if I miss some thing.
https://github.com/aws-quickstart/quickstart-trendmicro-deepsecurity/blob/master/templates/marketplace/dsm-mp.template#L248

**Comment by sshvans** [comment]
What error are you seeing? Can you paste the specific error you are seeing?

**Comment by kvaibhawa** [comment]
I cleaned up the stack and no more log but it seems right AMI at this comment. closing it now
